package testPackage;

import org.nlogo.api.Agent;
import org.nlogo.api.AgentSet;
import org.nlogo.api.Color;
import org.nlogo.agent.Patch;

import function mx.ecosur.netlogo.extensions.drools.helper.APIHelperFunctions.*;

dialect "java"

global String globalString;

rule "Print simple string"
	no-loop true
    when
        $str : String ()
        eval (null == globalString)
    then
        $str = "drools";
end

rule "Duplicate to Global"
	no-loop true
    when
        $str : String ()
        eval($str.equals(globalString))
    then
        globalString = "Global duplicate!";
        System.out.println(globalString);
end

rule "insert agents from agentset"
    when
        $aSet : AgentSet()
    then
        for (Agent a : $aSet.agents()) {
            insert(a);
        }
        retract ($aSet);
    end

    rule "color patches"
    when
        $patch : Patch(pcolorDouble == Color.Black)
    then
        $patch.pcolorDoubleUnchecked(new Double(77));
    end

    rule "set test field"
    when
        $patch : Patch()
        eval (GetVariable($patch, "test-field") == null)
    then
        SetVariable($patch, "test-field", new Double(22));
    end



