package testPackage;

import org.nlogo.api.Agent;
import org.nlogo.api.AgentSet;
import org.nlogo.api.Color;
import org.nlogo.agent.Patch;
import org.nlogo.api.Context;
import java.util.Random;

import function mx.ecosur.netlogo.extensions.drools.helper.APIHelperFunctions.*;

dialect "java"

global String globalString;

rule "Print simple string"
    no-loop true
    when
        $str : String ()
        eval (null == globalString)
    then
        $str = "drools";
end

rule "Duplicate to Global"
    no-loop true
    when
        $str : String ()
        eval($str.equals(globalString))
    then
        globalString = "Global duplicate!";
        System.out.println(globalString);
end

rule "insert agents from agentset"
    salience 100
    when
        $aSet : AgentSet()
    then
        for (Agent a : $aSet.agents()) {
            insert(a);
        }
        retract ($aSet);
end

rule "update some patches"
    when
        $context : Context()
        $patch : Patch(pcolorDouble == Color.Black, pxcor > 2, pycor > 2)
    then
        $patch.pcolorDoubleUnchecked(new Double(4.23));
        SetVariable($patch,"test-field", new Double (1.11));
end

rule "update other patches"
     when
        $context : Context()
        $patch : Patch(pcolorDouble == Color.Black)
    then
        $patch.pcolorDoubleUnchecked(new Double(48.23));
        SetVariable($patch,"test-field", new Double (1000.11));
end
